### ISSUE TITLE
Wiki: Add Link to Polygen Browser

### ISSUE THREAD

**Issue by tajmone** [alvisespano/Polygen#21]
https://github.com/pdonadeo/Polygen

(see #10)

**Comment by alvisespano** [comment]
Si mi fa piacere se riesci ad aggiungerlo alla wiki! E' proprio carino.

**Comment by tajmone** [comment]
Cercherò di farlo in giornata. Devo solo trovare un buco per avere il tempo di aggiungerlo in entrambi i Wiki (inglese ed italiano).

Siccome gestisco i Wiki tramite Git, devo aprire ogni volta i relativi progetti nell'editor e nel client grafico di Git, che alla fine consuma più tempo che non l'aggiunta del link stesso. Quindi ne approfitterò per sistemare anche le varie modifiche che mi sono annotate nella _TODO list_.

**Comment by alvisespano** [comment]
Tranquillo Tristano! Non c'è nessuna fretta! Quando puoi :)

**Comment by tajmone** [comment]
Fatto:

- https://github.com/alvisespano/Polygen/wiki#external-links
- https://github.com/tajmone/Polygen/wiki#link-esterni
