### ISSUE TITLE
Licenza Manuali?

### ISSUE THREAD

**Issue by tajmone** [alvisespano/Polygen#5]
Ho iniziato il lavoro di reimpaginazione dei manuali PolyGen per la crezione di grammatiche: quello in italiano, scaricato dal sito PolyGen (come pagina HTML), e quello inglese che ho trovato sul mirror di lapo.it:

- http://lapo.it/polygen/polygen-1.0.6-20040705-doc.zip

intitolato "HOWTO-grm, How to write a PolyGen grammar".

Li sto convertendo da HTML a pandoc markdown, di modo da poter usare pandoc e PP (un preprocessore per pandoc) per convertire poi il documento in HTML5 e anche altri formati. Questo dovrebbe semplificare la manutenzione dei manuali in futuro, nonché la conversione in svariati formati.

Nei manuali non ci sono riferimenti né all'autore né al traduttore all'inglese, e non vi è alcuna licenza.

Puoi confermarmi di essere l'autore del manuale italiano? E chi ha tradotto quello in inglese?

La versione inglese è incompleta (probabilmente si rifà ad una versione vecchia di PolyGen, dato che molte funzioni avanzate non sono riportare, ed anche la EBNF di PolyGen al fondo del documento è ridotta.). Sarebbe mia intenzione portare la versione inglese in pari con quella italiana, aggiungendo le sezioni mancanti.

Hai idea di che licenza abbiano i manuali? Per me andrebbe benissimo pubblicarli come publico dominio usando la Unlicense o la CC0 — ma ovviamente per fare questo devo sapere se l'autore e il traduttore sono d'accordo.

Appena chiarificato questi punti, volevo aprire un repository dedicato a questi manuali, così da pubblicare i sorgenti markdown, le macro e gli script necessari per creare i documenti finali. Posso pubblicare il tutto anche se i lavori sono ancora in corso (ed in alto mare), così i progressi sono visibili pubblicamente, e chi vuole può contribuire.

Poi potremo includere qui solo i documenti HTMl (ed eventuali altri formati) finiti.

**Comment by alvisespano** [comment]
Ho scritto tutto io: programma, manuale, testi del sito, sia in italiano
che in inglese.
Credo che la versione inglese non l'ho mai finita di allineare a quella
italiana, perché l'utenza internazionale all'epoca (2002-2003) non era
significativa.
Oggigiorno sarebbe opportuno che la traduzione inglese sia allineata con
quella italiana - hai voglia di farlo tu?


Il giorno 9 gennaio 2018 11:39, Tristano Ajmone <notifications@github.com>
ha scritto:

**Comment by alvisespano** [comment]
Mi spiego meglio: il mio amico Zeff ha fatto il sito e molte altre cose
legate ad esso. Tuttavia  l'autore del programma e dei manuali sono io,
questo intendevo.

Il giorno 9 gennaio 2018 11:42, Alvise Spanò <spano.alvise@gmail.com> ha
scritto:

**Comment by tajmone** [comment]
Ok, grazie.

Per l'inglese me occupo volentieri io (sono madrelingua).

Ho solo bisogno di sapere che licenza mettere per pubblicarli su GitHub (purtroppo me lo chiede alla creazione del repository). Nel README menzionerò la storia dei documenti, e poi nel testo finale potremo tranquillamente mettere (o omettere) la lista di chi ha contribuito ai documenti. Per ora specificarne nel README l'origine, l'autore e lo status di copyright e licenza dovrebbe bastare.

**Comment by alvisespano** [comment]
Non sono un grande esperto di licenze, ma credo sia il caso di mettere la medesima del polygen, cioè una GPL.

**Comment by alvisespano** [comment]
Ho cambiato i credits coi nomi veri e con una riga di ringraziamenti a te.

**Comment by tajmone** [comment]
Ottimo. La GPL andrà benissimo.

**Comment by tajmone** [comment]
Ok, ti aggiorno. Ci ho messo un bel po' di tempo, ma volevo fare le cose per bene (sul mio PC i file erano tutti disordinati, così ho dato un ripulata prima di pubblicare).

Questo è il nuovo progetto che raccoglierà i manuali PolyGen (ed eventuali altre documentazioni e tutorial):

- https://github.com/tajmone/polygen-docs/tree/draftwork/docs-src

Il lavoro per ora avviene nella branch `docs-src`, quando saranno pronti squasherò il tutto con un singolo commit in `master`. 

Ecco un'anteprima della bozza italiana:

- http://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/draftwork/docs-src/Polyman_IT.html

... è ancora imcompleta, ma rende l'idea di come sarà il documento finale (i colori della sintassi delle grammatiche sono provvisori, creerò un tema più chiaro, questo era giusto per partire e testare).

Come puoi vedere, ci sono un sacco di strumenti terze parti coinvolti nella conversione da markdown ad HTML (pandoc, PP, pandoc-crossref, e Highlight). Questi strumenti garantiscono una buona qualità del documento finale, nonché la conversione in vari formati (per ora mi concentro solo su HTML).

Per semplificare le cose, ho creato uno script che scarica automaticamente tutti i tools richiesti, e li estrae in un'apposita cartella rendendoli disponibili senza dover installare nulla. Quindi, basta un click e tutto l'ambiente di lavoro è pronto all'uso:

- https://github.com/tajmone/polygen-docs/tree/draftwork/docs-src/tools

Ok, questo parte (impostare l'ambiente di lavoro rendendolo accessibile ai potenziali contribuenti) era in realtà la parte più gravosa. Il resto è solo questione di tempo: adattare il testo italiano al nuovo formato, e poi quello inglese, etc.

Mi ci dedicherò nel tempo libero, e man mano che completero un pezzo lo committerò e pubblicherò; così che tu possa seguire i lavori in corso.

Dovrò cambiare leggermente il sistema della numerazione delle sezioni, per adattarlo a quello usato da pandoc e agli standard dello HTML5 (es: `1.0 -> 1`; `2.0.1 -> 2.1.1`, etc.) . Nulla che stravolga il documento; però renderà più semplice aggiungere nuove sezioni o capitoli in futuro, senza dover modificare i link dei rimandi interni alle varie sezioni.

**Comment by alvisespano** [comment]
Molto carino davvero! Magari per le parti più intricate che riguardano il
metalinguaggio del polygen, se ti serve assistenza, posso contribuire.
Esempi: il sistema di label, le regole di scoping dei let-binding locali,
lazy e strict, ecc.

Alvise

Il giorno 10 gennaio 2018 15:54, Tristano Ajmone <notifications@github.com>
ha scritto:

**Comment by tajmone** [comment]
> Magari per le parti più intricate che riguardano il
metalinguaggio del polygen, se ti serve assistenza, posso contribuire.
Esempi: il sistema di label, le regole di scoping dei let-binding locali,
lazy e strict, ecc.

Sì grazie. In effetti ho provato a fare qualche ricerca per capire quali termini adottare nelle parti inglese non tradotte (che introducono termini non ancora menzionati) e non ho trovato granché — ho ipotizzato che "weak binding" e "closure" potessero andar bene, ma ti interpellerò sicuramente in merito.

Ti sottopongo qui un problema che avevo già annotato da tempo:

### Simbolo Corrotto in Sez. 4.1.3

In tutte le versioni del manuale c'è un problema nella Sezione __4.1.3 Regole lessicali__:

- http://www.polygen.org/it/manuale#4.1.3_Regole_lessicali

Qualche problema con la codifica dei caratteri ha fatto sì che uno (forse due) caratteri siano andati persi e sostituiti dal carattere di rimpiazzo `�` (U+FFFD):

> #### 4.1.3 Regole lessicali
> 
> Seguono le regole lessicali in notazione di espressioni regolari di tipo 3.
> 
> ``` ebnf
> Term     ::= [a-z 0-9 '][a-z A-Z 0-9 ']*
>           |  " [A-Z a-z 0-9 ( ) _ - ? . , ! : \ & # + * / % $ � [ ] { } ~ @ ; : | < > = ^ ' \ "]* "
> 
> Nonterm  ::= [A-Z][A-Z a-z 0-9]*
> 
> Label    ::= [A-Z a-z 0-9]+
> 
> DotLabel ::= . Label
> ```

Avrei bisogno di una tua conferma su come riparare il carattere mancante.

Ho anlizzato i sorgenti, e credo di aver isolato la parte del codice che tratta i caratteri validi per un simbolo Terminale virgolettato ([`lexer.mll`][lexer.mll], 28–30):

``` ocaml
  | ['a'-'z' 'A'-'Z' '0'-'9' '!' '£' '$' '%' '&' '/' '(' ')' '=' '?' '^' '\''
     '[' ']' '*' '+' '@' '#' '<' '>' ',' '.' '-' ';' ':' '_' '{' '}' '`' '~'
     '|' ' ']       { let s = Lexing.lexeme lexbuf in s ^ (quote lexbuf) }
```


Se non erro, al posto del `�` dovrei mettere i simboli `£` e `` ` `` (in effetti, i simboli mancanti sono due, non uno).

Confermi?

[lexer.mll]: https://github.com/alvisespano/Polygen/blob/master/src/lexer.mll#L28

**Comment by alvisespano** [comment]
Non riesco a vedere i caratteri di cui parli: spiegami a che caratteri ti
riferisci.

Il giorno 10 gennaio 2018 16:18, Tristano Ajmone <notifications@github.com>
ha scritto:

**Comment by tajmone** [comment]
Per evidenziarlo, riporto di nuovo qui sotto la parte in questione, e inserisco il carattere perduto tra virgolette a caporale (`>>>>�<<<<`), seconda riga, un po' oltre il centro:

``` 
Term     ::= [a-z 0-9 '][a-z A-Z 0-9 ']*
          |  " [A-Z a-z 0-9 ( ) _ - ? . , ! : \ & # + * / % $ >>>>�<<<< [ ] { } ~ @ ; : | < > = ^ ' \ "]* "
Nonterm  ::= [A-Z][A-Z a-z 0-9]*
Label    ::= [A-Z a-z 0-9]+
DotLabel ::= . Label
```

**Comment by alvisespano** [comment]
Scusa avevo mal interpretato la tua mail in cui mi chiedevi del carattere,
e pensavo mi stessi dicendo che tu avevi trovato che carattere era - mentre
me lo stavi semplicemente chiedendo :)
Abbi pazienza ma al lavoro a volte leggo in fretta :P
Comunque, lo stato del DFA del lexer quando trova le virgolette diventa
"quote"; e in tale stato ci sono i caratteri £ e ` (il backtick) che
mancano all'appello, come dici tu.



2018-01-10 21:10 GMT+01:00 Tristano Ajmone <notifications@github.com>:

**Comment by tajmone** [comment]
Perfetto. Ho corretto, controlla se va bene:

- https://htmlpreview.github.io/?https://github.com/tajmone/polygen-docs/blob/draftwork/docs-src/Polyman_IT.html#regole-lessicali

Come puoi vedere, sono quasi in dirittura d'arrivo: mi mancano solo le ultime due tabelle dell'Appendice e poi ho terminato la prima bozza di riadattamento. La tabella grossa è un po' impestata da riprodurre in markdown, per via delle celle multiriga, ma dovrei farcela. Poi dovrò ritoccare il sistema di numerazione dei capitoli, per automatizzarlo e consentire riferimenti incrociati con link e numeri che si auto-aggiornano quando il documento cambia (per questo userò un filtro pandoc: [`pandoc-crossref`](http://lierdakil.github.io/pandoc-crossref/)). 

Per scrupolo, voglio anche provare ad eseguire i vari esempi in PolyGUI e verificare che siano tutti validi — ne ho trovato e corretto uno con una parentisi di troppo, piccole sviste di copia e incolla che possono essere sfuggite.

Devo anche mettere mano al CSS e ritoccare alcuni elementi, e usare un tema ad hoc per la sintassi PolyGen. Aggiungerò un modulo Sass per semplificare la cosa.

### Aggiunto Collaboratore `polygen-docs`

Ti ho aggiunto ai collaboratori del progetto documentazione, così puoi editare; e questo dovrebbe automaticamente farti ricevere notifiche per i nuovi Issue aperti, ed eventuali thread. Questo mi consentirà di spostare la discussione riguardo la documentazione da questo progetto all'altro — così evitiamo di intasare qui con thread non correlati.

Appena riceverò conferma della tua sottoscrizione a `polygen-docs`, proverò ad aprire lì un paio di issue riguardo questioni su cui volevo la tua opinione, e vedremo se ricevi le notifiche. Appurato ciò, potrò chiudere questo lunghissimo thread.

**Comment by tajmone** [comment]
Il lavoro di porting del manuale italiano è praticamente finito. Devo solo rileggere il testo a caccia di refusi e aggiungere una descrizione in cima. 

Intanto chiudo questo thread, eventuali nuovi issues li aprirò su [`polygen-docs`](https://github.com/tajmone/polygen-docs)
