### ISSUE TITLE
Binari per OSX

### ISSUE THREAD

**Issue by alvisespano** [alvisespano/Polygen#6]
Abbiamo un modo per compilare Polygen su OSX e impacchettare i binari assieme agli altri?

**Comment by tajmone** [comment]
Io putroppo non ho un Mac. Ma tra i miei vecchi file PolyGen che avevo scaricato dal tuo siti vedo un binario per Mac, anche se probabilmente è molto vecchio (2005?). Pensi che quel binario non funzionerebbe su un macOS moderno?

**Comment by alvisespano** [comment]
È una build vecchissima ma magari funziona ancora. Comunque conosco gente
che ha il mac e ci programma quindi potrei chiedere di ricompilare la 1.0.7
con un compilatore ocaml per osx recente

Il giorno lun 15 gen 2018 alle 10:45 Tristano Ajmone <
notifications@github.com> ha scritto:

**Comment by tajmone** [comment]
Scusa, non le avevo viste...

Non ho mai approfondito la conoscenza di Pandoc, ho delle domande:

> 1. i sorgenti dei doc sono i markdown ed il resto è artifatto di building?
> cosa devo installare per poter buildare?

Nella cartella `polygen-docs\docs-src\tools` trovi un cript batch che scarica e dezippa tutti i binari richiesti (richede 7-Zip e cURL sul sistema). Sempre in quella cartella, c'è un `README` con instruzioni dettagliate. Ma basta lanciare lo script e fa tutto lui.

> 2. Pandoc su Cygwin pare non ci sia.

Qui trovi i precompilati per tutti i vari OS:

https://github.com/jgm/pandoc/releases

... ma lo script del punto 1 è la soluzione più comoda.

> 3. il sottosistema di commenti (esempio: !comment{ FIXME -- poco chiaro}) è puramente in-source o c'è qualche tool esterno (visuale o meno) che li genera/gestisce?

Fa parte della macro PP, un preprocessore che s'interpone tra il sorgente markdown e pandoc:

https://github.com/CDSoft/pp

PP offre potenti macro di default, e consente anche di crearne di proprie, ampliando i potenziali di markdown. Per esempio, mi interfaccio a Highlight, un tool esterno per colare la sintassi, tramite una macro PP che passa il blocco di codice nel suo parametro al tool esterno, e restituisce il risultato nel documento.

**Comment by tajmone** [comment]
L'unico limite di PP è che i binari precompilati per Windows sono disponibli solo in versione 64 bit, e per chi ha un PC a 32 bit tocca compilarsi PP da Haskell.
